### ISSUE TITLE
The value of hwcpipe::device::constants.gpu_id is error

### ISSUE THREAD

**Issue by SheepHuan** [ARM-software/HWCPipe#67] opened 2023-09-10 12:57 UTC
The result of  hwcpipe::gpu::get_device_number() does not match with the value of hwcpipe::device::constants.gpu_id ,but the value of the fw_version matches with hwcpipe::gpu::get_device_number()。I tested hwcpipe's tag 2.1.0 branch on Dimensity8050.

My code is here.
```c++
void show_gpu_info(int gpu_id)
{
    hwcpipe::gpu gpu(gpu_id);
    hwcpipe::device::constants constants = gpu.get_constants();

    spdlog::info("gpu_id: {}", constants.gpu_id);
    spdlog::info("gpu_id: {}", constants.fw_version);
    spdlog::info("gpu_id: {}", gpu.get_device_number());

    spdlog::info("bus_width: {}", constants.axi_bus_width);
    spdlog::info("num_shader_cores: {}", constants.num_shader_cores);
    spdlog::info("shader_core_mask: {}", constants.shader_core_mask);
    spdlog::info("num_l2_slices: {}", constants.num_l2_slices);
    spdlog::info("l2_slice_size: {}", constants.l2_slice_size);
    spdlog::info("num_exec_engines: {}", constants.num_exec_engines);

    spdlog::info("tile_size: {}", constants.tile_size);
    spdlog::info("warp_width: {}", constants.warp_width);
}

```

Log is here
```text
[2023-09-10 20:46:48.140] [info] gpu_id: 36992
[2023-09-10 20:46:48.140] [info] gpu_id: 0
[2023-09-10 20:46:48.140] [info] gpu_id: 0
[2023-09-10 20:46:48.140] [info] bus_width: 128
[2023-09-10 20:46:48.140] [info] num_shader_cores: 9
[2023-09-10 20:46:48.140] [info] shader_core_mask: 6684775
[2023-09-10 20:46:48.140] [info] num_l2_slices: 4
[2023-09-10 20:46:48.141] [info] l2_slice_size: 262144
[2023-09-10 20:46:48.141] [info] num_exec_engines: 1
[2023-09-10 20:46:48.141] [info] tile_size: 16
[2023-09-10 20:46:48.141] [info] warp_width: 16
```

**Comment by solidpixel** [comment] 2023-09-14 16:49
> The result of hwcpipe::gpu::get_device_number() does not match with the value of hwcpipe::device::constants.gpu_id.

Why do you think it should? These are different things.

The `get_device_number()` function returns the device index - i.e. `/dev/mali0` returns 0, `/dev/mali1` returns 1. This is expected to return 0 unless you have multiple GPUs in the system.

The `gpu_id` is the product model ID for the GPU in the device.

**Comment by solidpixel** [comment] 2023-09-14 16:54
Closing; not a bug.

**Closed by solidpixel** 2023-09-14 16:54 UTC
