### ISSUE TITLE
build example error: 'device/product_id.hpp' file not found

### ISSUE THREAD

**Issue by FelixZhang00** [ARM-software/HWCPipe#75] opened 2024-04-21 07:50 UTC
➜  build git:(main) make                                        
[ 50%] Building CXX object CMakeFiles/api-example.dir/api_example.cpp.o
/Users/xxx/work/HWCPipe/examples/api_example.cpp:7:10: fatal error: 'device/product_id.hpp' file not found
#include <device/product_id.hpp>
         ^~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/api-example.dir/api_example.cpp.o] Error 1
make[1]: *** [CMakeFiles/api-example.dir/all] Error 2
make: *** [all] Error 2

**Comment by markbarnett-arm** [comment] 2024-04-22 10:19
Please can you provide some more information on how you are trying to configure and build the library? Is this being built as part of another program or are you trying to build the api-example on its own? What options did you choose when configuring the library?

**Comment by markbarnett-arm** [comment] 2024-06-12 10:43
Closing - could not reproduce this issue. I've re-tested with the latest version and it seems fine.

**Closed by markbarnett-arm** 2024-06-12 10:43 UTC
